Tuple=(10,25.5,1+5j,'hello','we','are','learning','python',[10,20,30])
print(Tuple)
#access tuple elements using +ve and -ve indexing
print("Accessing list elements using +ve elements")
print(Tuple[0])
print(Tuple[1])
print(Tuple[2])
print(Tuple[3])
print(Tuple[4])
print(Tuple[5])
print(Tuple[6])
print(Tuple[7])
print(Tuple[8])
print("Accessing list elements using -ve elements")
print(Tuple[0])
print(Tuple[-8])
print(Tuple[-7])
print(Tuple[-6])
print(Tuple[-5])
print(Tuple[-4])
print(Tuple[-3])
print(Tuple[-2])
print(Tuple[-1])
